### ISSUE TITLE
About selecting replay data

### ISSUE THREAD

**Issue by YangJae96** [g3956/PTKP#2]
Hi, thanks for your great work.

I was wondering why do you only save data from only right before domain?

For example, when you train with msmt17 dataset, you only save cuhk-sysu data for replay.

Is there a particular reason?

**Comment by g3956** [comment]
Thanks for your interest in our work.

In fact, we **add** the data of the last domain into a global variable.
So all the data from previous domains are used for replay.

For the sampling strategy, we sample 128 images for each previous domain.
