### ISSUE TITLE
About old model and distill loss

### ISSUE THREAD

**Issue by YangJae96** [g3956/PTKP#3]
Hi, thanks for your great work.

I read the paper and the code implementation.

I was wondering if creating **old model** and constructing **knowledge distillation** loss between old and new model a 
essential setting in lifelong re-ID.

Couldn't you just input the **replay data** into only **new model** and give supervision??
Does this way viloate the lifelong re-ID problem setting?

**Comment by g3956** [comment]
Thanks for your interest in our work.

Regarding the first question, it is essential to distill knowledge from the old model to the new one to preserve previous knowledge.

Regarding the second question, if we input the replay data into the new model, the supervision is also the prediction, which is non-sense.

Regarding the third question, do you mean that preserving replay data violates the setting of lifelong re-ID?
